### ISSUE TITLE
Shooting hookshot at Pixelmon mobs crashes server, client and corrupts chunk

### ISSUE THREAD

**Issue by SullyTheUnusual** [Chocolatin/Better-Dungeons#2]
Is there any way to just disable the hookshot from the mod?  There aren't individual item IDs in the configs, and deleting the item classes from the mod zip just makes the server crash when starting.

**Comment by Chocolatin** [comment]
Contact with Pixelmon creators and ask them to check if the ridding entity of their mobs instace of EntityLivingBase.
´There is no way to disable the hooks.

**Comment by JayPeaSize** [comment]
Not an issue on our (pixelmon's) end.

**Comment by SullyTheUnusual** [comment]
So, is this being looked into?  Very nasty world-corrupting crashes...
